/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as HistoryIdEditRouteImport } from './routes/history.$id.edit'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryIdEditRoute = HistoryIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HistoryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/capture': typeof CaptureRoute
  '/history': typeof HistoryRouteWithChildren
  '/stats': typeof StatsRoute
  '/history/$id': typeof HistoryIdRouteWithChildren
  '/history/$id/edit': typeof HistoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/capture': typeof CaptureRoute
  '/history': typeof HistoryRouteWithChildren
  '/stats': typeof StatsRoute
  '/history/$id': typeof HistoryIdRouteWithChildren
  '/history/$id/edit': typeof HistoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/capture': typeof CaptureRoute
  '/history': typeof HistoryRouteWithChildren
  '/stats': typeof StatsRoute
  '/history/$id': typeof HistoryIdRouteWithChildren
  '/history/$id/edit': typeof HistoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/capture'
    | '/history'
    | '/stats'
    | '/history/$id'
    | '/history/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/capture'
    | '/history'
    | '/stats'
    | '/history/$id'
    | '/history/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/capture'
    | '/history'
    | '/stats'
    | '/history/$id'
    | '/history/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CaptureRoute: typeof CaptureRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$id/edit': {
      id: '/history/$id/edit'
      path: '/edit'
      fullPath: '/history/$id/edit'
      preLoaderRoute: typeof HistoryIdEditRouteImport
      parentRoute: typeof HistoryIdRoute
    }
  }
}

interface HistoryIdRouteChildren {
  HistoryIdEditRoute: typeof HistoryIdEditRoute
}

const HistoryIdRouteChildren: HistoryIdRouteChildren = {
  HistoryIdEditRoute: HistoryIdEditRoute,
}

const HistoryIdRouteWithChildren = HistoryIdRoute._addFileChildren(
  HistoryIdRouteChildren,
)

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRouteWithChildren
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRouteWithChildren,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CaptureRoute: CaptureRoute,
  HistoryRoute: HistoryRouteWithChildren,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
